'use client'
// import { Inter } from "next/font/google";
import { Outfit } from "next/font/google";// To set Font
import "./globals.css";
import { PayPalScriptProvider } from "@paypal/react-paypal-js";
import { Provider } from "react-redux";
import { store } from "./redux/store";
import ReduxWrapper from "./_components/ReduxWrapper";

const outfit = Outfit({ subsets: ["latin"] });

//We cannot use this metadata in client side.
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const initialOptions = {
    clientId: process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID,
    // Add other options as needed
  };

  console.log('this is layout page')

  return (

    <html lang="en" className="hydrated">
      <PayPalScriptProvider options={initialOptions}>
        <body className={`${outfit.className}`}>
          <Provider store={store}>
            <ReduxWrapper>
              {children}
            </ReduxWrapper>
          </Provider>
        </body>
      </PayPalScriptProvider >
    </html>

  );
}
